[python]
version = "3.12.3"

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.setup]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python -m gunicorn config.wsgi:application --bind 0.0.0.0:${PORT}"
