[python]
version = "3.12.3"

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.setup]
cmds = [
  # Don't run collectstatic here - Django may not be installed yet
  # It will run in the start command instead
]

[start]
cmd = "python manage.py collectstatic --noinput && python -m gunicorn config.wsgi:application --bind 0.0.0.0:${PORT}"
